package com.mrcookies.simplerunning.core

object Constants {

    const val REQUEST_CODE_LOCATION_PERMISSION = 0

    const val ACTION_START_RESUME_SERVICE="ACTION_START_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE="ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE="ACTION_STOP_SERVICE"
    const val ACTION_SHOW_TRACKING_ACTIVITY="ACTION_SHOW_TRACKING"

    const val MAX_LOCATION_UPDATE_INTERVAL = 5000L
    const val MIN_LOCATION_UPDATE_INTERVAL = 2000L
    const val TIMER_UPDATE_INTERVAL = 50L

    const val POLYLINE_WIDTH = 8f
    const val MAP_ZOOM = 15f

    const val NOTIFICATION_CHANNEL_ID ="TRACKING_CHANNEL"
    const val NOTIFICATION_CHANNEL_NAME ="TRACKING"
    const val NOTIFICATION_ID = 1
}